# Generated by Django 2.2.1 on 2020-11-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201121_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cartegorys',
            field=models.CharField(choices=[('not-specified', 'Not Specified'), ('male', 'Male'), ('female', 'Female')], default='', max_length=100, null=True),
        ),
    ]
