# Generated by Django 2.2.1 on 2020-11-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201121_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cartegorys',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('2category', '2category'), ('3category', '3category'), ('1category', '1category')], default='', max_length=100, null=True),
        ),
    ]
