# Generated by Django 2.2.1 on 2020-11-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201121_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Security_Wargame', 'Security_Wargame'), ('Security_Study', 'Security_Study'), ('Development_Study', 'Development_Study'), ('Other', 'Other'), ('Development_Programming', 'Development_Programming'), ('Security_CTF', 'Security_CTF')], default='none', max_length=100, null=True),
        ),
    ]
