# Generated by Django 2.2.1 on 2020-11-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201124_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Development_Programming', 'Development_Programming'), ('Security_CTF', 'Security_CTF'), ('Other', 'Other'), ('Security_Wargame', 'Security_Wargame'), ('Development_Study', 'Development_Study'), ('Security_Study', 'Security_Study')], default='none', max_length=100, null=True),
        ),
    ]
